package studio.bowman.gamblegame;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;

public class Inventory extends AppCompatActivity {

    int balance, keys;
    int emeralds, rubies, royalstones;
    int emeraldrings, rubyrings, royalrings;
    int backpack1, backpack2, backpack3, backpack4, backpack5, backpack6, backpack7, backpack8, backpack9;
    int anvil1, anvil2, anvil3;
    int pig1, pigroyalstone;
    int vault, vaultruby;
    int bank1, bankgold;
    int shield1, shield1_1, shield1_2, shield2, shield3, shield3royalstone, shield4;
    int watch1, watch1gold, watch1_1, watch2, watch3;
    int shovel1, shovel1royalstone, shovel2, shovel2gold, shovel3;
    int mask1, mask1whiteruby, mask2;
    int crowngold, crownroyalstone, crownwhiteruby;

    ImageView banneris;
    ImageButton leftBtn, mainBtn, rightBtn;
    ImageButton box1, box2, box3, box4, box5, box6, box7, box8, box9, box10, box11, box12, box13, box14, box15, box16, box17, box18, box19, box20, box21, box22, box23, box24, box25, box26, box27, box28, box29, box30, box31, box32, box33, box34, box35, box36,box37,box38,box39,box40,box41,box42,box43,box44,box45,box46,box47,box48,box49,box50,box51,box52,box53,box54,box55,box56,box57,box58,box59,box60,box61,box62,box63,box64,box65,box66,box67,box68,box69;
    ImageView back1, back2, back3, back4, back5, back6, back7, back8, back9, back10, back11, back12, back13, back14, back15, back16, back17, back18, back19, back20, back21, back22, back23, back24, back25, back26, back27, back28, back29, back30, back31, back32, back33, back34, back35, back36,back37,back38,back39,back40,back41,back42,back43,back44,back45,back46,back47,back48,back49,back50,back51,back52,back53,back54,back55,back56,back57,back58,back59,back60,back61,back62,back63,back64,back65,back66,back67,back68,back69;
    TextView count1, count2, count3, count4, count5, count6, count7, count8, count9, count10, count11, count12, count13, count14, count15, count16, count17, count18, count19, count20, count21, count22, count23, count24, count25, count26, count27, count28, count29, count30, count31, count32, count33, count34, count35, count36,count37,count38,count39,count40,count41,count42,count43,count44,count45,count46,count47,count48,count49,count50,count51,count52,count53,count54,count55,count56,count57,count58,count59,count60,count61,count62,count63,count64,count65,count66,count67,count68,count69;


    void setGUI(){
        box1.setImageResource(R.drawable.item_emerald);
        box2.setImageResource(R.drawable.item_ruby);
        box3.setImageResource(R.drawable.item_royalstone);
        box4.setImageResource(R.drawable.item_ring_emerald);
        box5.setImageResource(R.drawable.item_ring_ruby);
        box6.setImageResource(R.drawable.item_ring_royalstone);
        box7.setImageResource(R.drawable.item_crown_gold);
        box8.setImageResource(R.drawable.item_crown_ruby);
        box9.setImageResource(R.drawable.item_crown_royalstone);
        box10.setImageResource(R.drawable.item_anvil_1);
        box11.setImageResource(R.drawable.item_anvil_2);
        box12.setImageResource(R.drawable.item_anvil_2_whiteruby);
        box13.setImageResource(R.drawable.item_backpack1);
        box14.setImageResource(R.drawable.item_backpack2);
        box15.setImageResource(R.drawable.item_backpack3);
        box16.setImageResource(R.drawable.item_backpack4);
        box17.setImageResource(R.drawable.item_backpack5);
        box18.setImageResource(R.drawable.item_backpack6);
        box19.setImageResource(R.drawable.item_bank);
        box20.setImageResource(R.drawable.item_bank_gold);
        box21.setImageResource(R.drawable.case_check_1);
        box22.setImageResource(R.drawable.case_check_1);
        box23.setImageResource(R.drawable.case_check_1);
        box24.setImageResource(R.drawable.item_shield_1);
        box25.setImageResource(R.drawable.item_shield_1_1);
        box26.setImageResource(R.drawable.item_shield_1_2);
        box27.setImageResource(R.drawable.item_shield_2);
        box28.setImageResource(R.drawable.item_shield_3);
        box29.setImageResource(R.drawable.item_shield_3_royalstone);
        box30.setImageResource(R.drawable.item_shield_4);
        box31.setImageResource(R.drawable.item_shovel);
        box32.setImageResource(R.drawable.item_shovel_1_royalstone);
        box33.setImageResource(R.drawable.item_shovel_2);
        box34.setImageResource(R.drawable.item_shovel_2_gold);
        box35.setImageResource(R.drawable.item_shovel_3);
        box36.setImageResource(R.drawable.item_watch_1_1);
        box37.setImageResource(R.drawable.item_watch_1);
        box38.setImageResource(R.drawable.item_watch_1_gold);
        box39.setImageResource(R.drawable.item_watch_2);
        box40.setImageResource(R.drawable.item_watch_3);
        box41.setImageResource(R.drawable.case_check_1);
        box42.setImageResource(R.drawable.case_check_1);
        box43.setImageResource(R.drawable.case_check_1);
        box44.setImageResource(R.drawable.case_check_1);
        box45.setImageResource(R.drawable.case_check_1);
        box46.setImageResource(R.drawable.case_check_1);
        box47.setImageResource(R.drawable.case_check_1);
        box48.setImageResource(R.drawable.case_check_1);
        box49.setImageResource(R.drawable.case_check_1);
        box50.setImageResource(R.drawable.case_check_1);
        box51.setImageResource(R.drawable.case_check_1);
        box52.setImageResource(R.drawable.case_check_1);
        box53.setImageResource(R.drawable.case_check_1);
        box54.setImageResource(R.drawable.case_check_1);
        box55.setImageResource(R.drawable.case_check_1);
        box56.setImageResource(R.drawable.case_check_1);
        box57.setImageResource(R.drawable.case_check_1);
        box58.setImageResource(R.drawable.case_check_1);
        box59.setImageResource(R.drawable.case_check_1);
        box60.setImageResource(R.drawable.case_check_1);
        box61.setImageResource(R.drawable.case_check_1);
        box62.setImageResource(R.drawable.case_check_1);
        box63.setImageResource(R.drawable.case_check_1);
        box64.setImageResource(R.drawable.case_check_1);
        box65.setImageResource(R.drawable.case_check_1);
        box66.setImageResource(R.drawable.case_check_1);
        box67.setImageResource(R.drawable.case_check_1);
        box68.setImageResource(R.drawable.case_check_1);
        box69.setImageResource(R.drawable.case_check_1);

        back1.setImageResource(R.drawable.back);
        back2.setImageResource(R.drawable.back);
        back3.setImageResource(R.drawable.back);
        back4.setImageResource(R.drawable.back);
        back5.setImageResource(R.drawable.back);
        back6.setImageResource(R.drawable.back);
        back7.setImageResource(R.drawable.back);
        back8.setImageResource(R.drawable.back);
        back9.setImageResource(R.drawable.back);
        back10.setImageResource(R.drawable.back);
        back11.setImageResource(R.drawable.back);
        back12.setImageResource(R.drawable.back);
        back13.setImageResource(R.drawable.back);
        back14.setImageResource(R.drawable.back);
        back15.setImageResource(R.drawable.back);
        back15.setImageResource(R.drawable.back);
        back16.setImageResource(R.drawable.back);
        back17.setImageResource(R.drawable.back);
        back18.setImageResource(R.drawable.back);
        back19.setImageResource(R.drawable.back);
        back20.setImageResource(R.drawable.back);
        back21.setImageResource(R.drawable.back);
        back22.setImageResource(R.drawable.back);
        back23.setImageResource(R.drawable.back);
        back24.setImageResource(R.drawable.back);
        back25.setImageResource(R.drawable.back);
        back26.setImageResource(R.drawable.back);
        back27.setImageResource(R.drawable.back);
        back28.setImageResource(R.drawable.back);
        back29.setImageResource(R.drawable.back);
        back30.setImageResource(R.drawable.back);
        back31.setImageResource(R.drawable.back);
        back32.setImageResource(R.drawable.back);
        back33.setImageResource(R.drawable.back);
        back34.setImageResource(R.drawable.back);
        back35.setImageResource(R.drawable.back);
        back36.setImageResource(R.drawable.back);
        back37.setImageResource(R.drawable.back);
        back38.setImageResource(R.drawable.back);
        back39.setImageResource(R.drawable.back);
        back40.setImageResource(R.drawable.back);
        back41.setImageResource(R.drawable.back);
        back42.setImageResource(R.drawable.back);
        back43.setImageResource(R.drawable.back);
        back44.setImageResource(R.drawable.back);
        back45.setImageResource(R.drawable.back);
        back46.setImageResource(R.drawable.back);
        back47.setImageResource(R.drawable.back);
        back48.setImageResource(R.drawable.back);
        back49.setImageResource(R.drawable.back);
        back50.setImageResource(R.drawable.back);
        back51.setImageResource(R.drawable.back);
        back52.setImageResource(R.drawable.back);
        back53.setImageResource(R.drawable.back);
        back54.setImageResource(R.drawable.back);
        back55.setImageResource(R.drawable.back);
        back56.setImageResource(R.drawable.back);
        back57.setImageResource(R.drawable.back);
        back58.setImageResource(R.drawable.back);
        back59.setImageResource(R.drawable.back);
        back60.setImageResource(R.drawable.back);
        back61.setImageResource(R.drawable.back);
        back62.setImageResource(R.drawable.back);
        back63.setImageResource(R.drawable.back);
        back64.setImageResource(R.drawable.back);
        back65.setImageResource(R.drawable.back);
        back66.setImageResource(R.drawable.back);
        back67.setImageResource(R.drawable.back);
        back68.setImageResource(R.drawable.back);
        back69.setImageResource(R.drawable.back);

        box1.setAdjustViewBounds(true);
        box1.setPadding(0,0,0,0);
        box2.setAdjustViewBounds(true);
        box2.setPadding(0,0,0,0);
        box3.setAdjustViewBounds(true);
        box3.setPadding(0,0,0,0);
        box4.setAdjustViewBounds(true);
        box4.setPadding(0,0,0,0);
        box5.setAdjustViewBounds(true);
        box5.setPadding(0,0,0,0);
        box6.setAdjustViewBounds(true);
        box6.setPadding(0,0,0,0);
        box7.setAdjustViewBounds(true);
        box7.setPadding(0,0,0,0);
        box8.setAdjustViewBounds(true);
        box8.setPadding(0,0,0,0);
        box9.setAdjustViewBounds(true);
        box9.setPadding(0,0,0,0);
        box10.setAdjustViewBounds(true);
        box10.setPadding(0,0,0,0);
        box11.setAdjustViewBounds(true);
        box11.setPadding(0,0,0,0);
        box12.setAdjustViewBounds(true);
        box12.setPadding(0,0,0,0);
        box13.setAdjustViewBounds(true);
        box13.setPadding(0,0,0,0);
        box14.setAdjustViewBounds(true);
        box14.setPadding(0,0,0,0);
        box15.setAdjustViewBounds(true);
        box15.setPadding(0,0,0,0);
        box15.setAdjustViewBounds(true);
        box15.setPadding(0,0,0,0);
        box16.setAdjustViewBounds(true);
        box16.setPadding(0,0,0,0);
        box17.setAdjustViewBounds(true);
        box17.setPadding(0,0,0,0);
        box18.setAdjustViewBounds(true);
        box18.setPadding(0,0,0,0);
        box19.setAdjustViewBounds(true);
        box19.setPadding(0,0,0,0);
        box20.setAdjustViewBounds(true);
        box20.setPadding(0,0,0,0);
        box21.setAdjustViewBounds(true);
        box21.setPadding(0,0,0,0);
        box22.setAdjustViewBounds(true);
        box22.setPadding(0,0,0,0);
        box23.setAdjustViewBounds(true);
        box23.setPadding(0,0,0,0);
        box24.setAdjustViewBounds(true);
        box24.setPadding(0,0,0,0);
        box25.setAdjustViewBounds(true);
        box25.setPadding(0,0,0,0);
        box26.setAdjustViewBounds(true);
        box26.setPadding(0,0,0,0);
        box27.setAdjustViewBounds(true);
        box27.setPadding(0,0,0,0);
        box28.setAdjustViewBounds(true);
        box28.setPadding(0,0,0,0);
        box29.setAdjustViewBounds(true);
        box29.setPadding(0,0,0,0);
        box30.setAdjustViewBounds(true);
        box30.setPadding(0,0,0,0);
        box31.setAdjustViewBounds(true);
        box31.setPadding(0,0,0,0);
        box32.setAdjustViewBounds(true);
        box32.setPadding(0,0,0,0);
        box33.setAdjustViewBounds(true);
        box33.setPadding(0,0,0,0);
        box34.setAdjustViewBounds(true);
        box34.setPadding(0,0,0,0);
        box35.setAdjustViewBounds(true);
        box35.setPadding(0,0,0,0);
        box36.setAdjustViewBounds(true);
        box36.setPadding(0,0,0,0);
        box37.setAdjustViewBounds(true);
        box37.setPadding(0,0,0,0);
        box38.setAdjustViewBounds(true);
        box38.setPadding(0,0,0,0);
        box39.setAdjustViewBounds(true);
        box39.setPadding(0,0,0,0);
        box40.setAdjustViewBounds(true);
        box40.setPadding(0,0,0,0);
        box41.setAdjustViewBounds(true);
        box41.setPadding(0,0,0,0);
        box42.setAdjustViewBounds(true);
        box42.setPadding(0,0,0,0);
        box43.setAdjustViewBounds(true);
        box43.setPadding(0,0,0,0);
        box44.setAdjustViewBounds(true);
        box44.setPadding(0,0,0,0);
        box45.setAdjustViewBounds(true);
        box45.setPadding(0,0,0,0);
        box46.setAdjustViewBounds(true);
        box46.setPadding(0,0,0,0);
        box47.setAdjustViewBounds(true);
        box47.setPadding(0,0,0,0);
        box48.setAdjustViewBounds(true);
        box48.setPadding(0,0,0,0);
        box49.setAdjustViewBounds(true);
        box49.setPadding(0,0,0,0);
        box50.setAdjustViewBounds(true);
        box50.setPadding(0,0,0,0);
        box51.setAdjustViewBounds(true);
        box51.setPadding(0,0,0,0);
        box52.setAdjustViewBounds(true);
        box52.setPadding(0,0,0,0);
        box53.setAdjustViewBounds(true);
        box53.setPadding(0,0,0,0);
        box54.setAdjustViewBounds(true);
        box54.setPadding(0,0,0,0);
        box55.setAdjustViewBounds(true);
        box55.setPadding(0,0,0,0);
        box56.setAdjustViewBounds(true);
        box56.setPadding(0,0,0,0);
        box57.setAdjustViewBounds(true);
        box57.setPadding(0,0,0,0);
        box58.setAdjustViewBounds(true);
        box58.setPadding(0,0,0,0);
        box59.setAdjustViewBounds(true);
        box59.setPadding(0,0,0,0);
        box60.setAdjustViewBounds(true);
        box60.setPadding(0,0,0,0);
        box61.setAdjustViewBounds(true);
        box61.setPadding(0,0,0,0);
        box62.setAdjustViewBounds(true);
        box62.setPadding(0,0,0,0);
        box63.setAdjustViewBounds(true);
        box63.setPadding(0,0,0,0);
        box64.setAdjustViewBounds(true);
        box64.setPadding(0,0,0,0);
        box65.setAdjustViewBounds(true);
        box65.setPadding(0,0,0,0);
        box66.setAdjustViewBounds(true);
        box66.setPadding(0,0,0,0);
        box67.setAdjustViewBounds(true);
        box67.setPadding(0,0,0,0);
        box68.setAdjustViewBounds(true);
        box68.setPadding(0,0,0,0);
        box69.setAdjustViewBounds(true);
        box69.setPadding(0,0,0,0);

        back1.setAdjustViewBounds(true);
        back1.setPadding(0,0,0,0);
        back2.setAdjustViewBounds(true);
        back2.setPadding(0,0,0,0);
        back3.setAdjustViewBounds(true);
        back3.setPadding(0,0,0,0);
        back4.setAdjustViewBounds(true);
        back4.setPadding(0,0,0,0);
        back5.setAdjustViewBounds(true);
        back5.setPadding(0,0,0,0);
        back6.setAdjustViewBounds(true);
        back6.setPadding(0,0,0,0);
        back7.setAdjustViewBounds(true);
        back7.setPadding(0,0,0,0);
        back8.setAdjustViewBounds(true);
        back8.setPadding(0,0,0,0);
        back9.setAdjustViewBounds(true);
        back9.setPadding(0,0,0,0);
        back10.setAdjustViewBounds(true);
        back10.setPadding(0,0,0,0);
        back11.setAdjustViewBounds(true);
        back11.setPadding(0,0,0,0);
        back12.setAdjustViewBounds(true);
        back12.setPadding(0,0,0,0);
        back13.setAdjustViewBounds(true);
        back13.setPadding(0,0,0,0);
        back14.setAdjustViewBounds(true);
        back14.setPadding(0,0,0,0);
        back15.setAdjustViewBounds(true);
        back15.setPadding(0,0,0,0);
        back15.setAdjustViewBounds(true);
        back15.setPadding(0,0,0,0);
        back16.setAdjustViewBounds(true);
        back16.setPadding(0,0,0,0);
        back17.setAdjustViewBounds(true);
        back17.setPadding(0,0,0,0);
        back18.setAdjustViewBounds(true);
        back18.setPadding(0,0,0,0);
        back19.setAdjustViewBounds(true);
        back19.setPadding(0,0,0,0);
        back20.setAdjustViewBounds(true);
        back20.setPadding(0,0,0,0);
        back21.setAdjustViewBounds(true);
        back21.setPadding(0,0,0,0);
        back22.setAdjustViewBounds(true);
        back22.setPadding(0,0,0,0);
        back23.setAdjustViewBounds(true);
        back23.setPadding(0,0,0,0);
        back24.setAdjustViewBounds(true);
        back24.setPadding(0,0,0,0);
        back25.setAdjustViewBounds(true);
        back25.setPadding(0,0,0,0);
        back26.setAdjustViewBounds(true);
        back26.setPadding(0,0,0,0);
        back27.setAdjustViewBounds(true);
        back27.setPadding(0,0,0,0);
        back28.setAdjustViewBounds(true);
        back28.setPadding(0,0,0,0);
        back29.setAdjustViewBounds(true);
        back29.setPadding(0,0,0,0);
        back30.setAdjustViewBounds(true);
        back30.setPadding(0,0,0,0);
        back31.setAdjustViewBounds(true);
        back31.setPadding(0,0,0,0);
        back32.setAdjustViewBounds(true);
        back32.setPadding(0,0,0,0);
        back33.setAdjustViewBounds(true);
        back33.setPadding(0,0,0,0);
        back34.setAdjustViewBounds(true);
        back34.setPadding(0,0,0,0);
        back35.setAdjustViewBounds(true);
        back35.setPadding(0,0,0,0);
        back36.setAdjustViewBounds(true);
        back36.setPadding(0,0,0,0);
        back37.setAdjustViewBounds(true);
        back37.setPadding(0,0,0,0);
        back38.setAdjustViewBounds(true);
        back38.setPadding(0,0,0,0);
        back39.setAdjustViewBounds(true);
        back39.setPadding(0,0,0,0);
        back40.setAdjustViewBounds(true);
        back40.setPadding(0,0,0,0);
        back41.setAdjustViewBounds(true);
        back41.setPadding(0,0,0,0);
        back42.setAdjustViewBounds(true);
        back42.setPadding(0,0,0,0);
        back43.setAdjustViewBounds(true);
        back43.setPadding(0,0,0,0);
        back44.setAdjustViewBounds(true);
        back44.setPadding(0,0,0,0);
        back45.setAdjustViewBounds(true);
        back45.setPadding(0,0,0,0);
        back46.setAdjustViewBounds(true);
        back46.setPadding(0,0,0,0);
        back47.setAdjustViewBounds(true);
        back47.setPadding(0,0,0,0);
        back48.setAdjustViewBounds(true);
        back48.setPadding(0,0,0,0);
        back49.setAdjustViewBounds(true);
        back49.setPadding(0,0,0,0);
        back50.setAdjustViewBounds(true);
        back50.setPadding(0,0,0,0);
        back51.setAdjustViewBounds(true);
        back51.setPadding(0,0,0,0);
        back52.setAdjustViewBounds(true);
        back52.setPadding(0,0,0,0);
        back53.setAdjustViewBounds(true);
        back53.setPadding(0,0,0,0);
        back54.setAdjustViewBounds(true);
        back54.setPadding(0,0,0,0);
        back55.setAdjustViewBounds(true);
        back55.setPadding(0,0,0,0);
        back56.setAdjustViewBounds(true);
        back56.setPadding(0,0,0,0);
        back57.setAdjustViewBounds(true);
        back57.setPadding(0,0,0,0);
        back58.setAdjustViewBounds(true);
        back58.setPadding(0,0,0,0);
        back59.setAdjustViewBounds(true);
        back59.setPadding(0,0,0,0);
        back60.setAdjustViewBounds(true);
        back60.setPadding(0,0,0,0);
        back61.setAdjustViewBounds(true);
        back61.setPadding(0,0,0,0);
        back62.setAdjustViewBounds(true);
        back62.setPadding(0,0,0,0);
        back63.setAdjustViewBounds(true);
        back63.setPadding(0,0,0,0);
        back64.setAdjustViewBounds(true);
        back64.setPadding(0,0,0,0);
        back65.setAdjustViewBounds(true);
        back65.setPadding(0,0,0,0);
        back66.setAdjustViewBounds(true);
        back66.setPadding(0,0,0,0);
        back67.setAdjustViewBounds(true);
        back67.setPadding(0,0,0,0);
        back68.setAdjustViewBounds(true);
        back68.setPadding(0,0,0,0);
        back69.setAdjustViewBounds(true);
        back69.setPadding(0,0,0,0);
        

        banneris.setImageResource(R.drawable.case_title_exquisite);
        leftBtn.setImageResource(R.drawable.shop_icon);
        mainBtn.setImageResource(R.drawable.inventory_icon_active);
        rightBtn.setImageResource(R.drawable.cases_icon);

        banneris.setAdjustViewBounds(true);
        banneris.setPadding(0,0,0,0);
        leftBtn.setAdjustViewBounds(true);
        leftBtn.setPadding(0,0,0,0);
        mainBtn.setAdjustViewBounds(true);
        mainBtn.setPadding(0,0,0,0);
        rightBtn.setAdjustViewBounds(true);
        rightBtn.setPadding(0,0,0,0);
    }
    void updateDisplay(){
        count1.setText("" + emeralds);
        count2.setText("" + rubies);
        count3.setText("" + royalstones);
        count4.setText("" + emeraldrings);
        count5.setText("" + rubyrings);
        count6.setText("" + royalrings);
        count7.setText("" + crowngold);
        count8.setText("" + crownwhiteruby);
        count9.setText("" + crownroyalstone);
        count10.setText("" + balance);
        count11.setText("" + balance);
        count12.setText("" + balance);
        count13.setText("" + balance);
        count14.setText("" + balance);
        count15.setText("" + balance);
        count16.setText("" + balance);
        count17.setText("" + balance);
        count18.setText("" + balance);
        count19.setText("" + balance);
        count20.setText("" + balance);
        count21.setText("" + balance);
        count22.setText("" + balance);
        count23.setText("" + balance);
        count24.setText("" + balance);
        count25.setText("" + balance);
        count26.setText("" + balance);
        count27.setText("" + balance);
        count28.setText("" + balance);
        count29.setText("" + balance);
        count30.setText("" + balance);
        count31.setText("" + balance);
        count32.setText("" + balance);
        count33.setText("" + balance);
        count34.setText("" + balance);
        count35.setText("" + balance);
        count36.setText("" + balance);
        count37.setText("" + balance);
        count38.setText("" + balance);
        count39.setText("" + balance);
        count40.setText("" + balance);
        count41.setText("" + balance);
        count42.setText("" + balance);
        count43.setText("" + balance);
        count44.setText("" + balance);
        count45.setText("" + balance);
        count46.setText("" + balance);
        count47.setText("" + balance);
        count48.setText("" + balance);
        count49.setText("" + balance);
        count50.setText("" + balance);
        count51.setText("" + balance);
        count52.setText("" + balance);
        count53.setText("" + balance);
        count54.setText("" + balance);
        count55.setText("" + balance);
        count56.setText("" + balance);
        count57.setText("" + balance);
        count58.setText("" + balance);
        count59.setText("" + balance);
        count60.setText("" + balance);
        count61.setText("" + balance);
        count62.setText("" + balance);
        count63.setText("" + balance);
        count64.setText("" + balance);
        count65.setText("" + balance);
        count66.setText("" + balance);
        count67.setText("" + balance);
        count68.setText("" + balance);
        count69.setText("" + balance);
    }

    void loadData(){
        SharedPreferences load = getSharedPreferences("Database", Context.MODE_PRIVATE);
        balance = load.getInt("balance", 0);
        keys = load.getInt("balance", 0);

        emeralds = load.getInt("emeralds", 0);
        rubies = load.getInt("rubies", 0);
        royalstones = load.getInt("royalstones", 0);

        emeraldrings = load.getInt("emeraldrings", 0);
        rubyrings = load.getInt("rubyrings", 0);
        royalrings = load.getInt("royalrings", 0);

        backpack1 = load.getInt("backpack1", 0);
        backpack2 = load.getInt("backpack2", 0);
        backpack3 = load.getInt("backpack3", 0);
        backpack4 = load.getInt("backpack4", 0);
        backpack5 = load.getInt("backpack5", 0);
        backpack6 = load.getInt("backpack6", 0);
        backpack7 = load.getInt("backpack7", 0);
        backpack8 = load.getInt("backpack8", 0);
        backpack9 = load.getInt("backpack9", 0);

        anvil1 = load.getInt("anvil1", 0);
        anvil2 = load.getInt("anvil2", 0);
        anvil3 = load.getInt("anvil3", 0);

        pig1 = load.getInt("pig1", 0);
        pigroyalstone = load.getInt("pigroyalstone", 0);

        vault = load.getInt("vault", 0);
        vaultruby = load.getInt("vaultruby", 0);

        bank1 = load.getInt("bank1", 0);
        bankgold = load.getInt("bankgold", 0);

        shield1 = load.getInt("shield1", 0);
        shield1_1 = load.getInt("shield1_1", 0);
        shield1_2 = load.getInt("shield1_2", 0);
        shield2 = load.getInt("shield2", 0);
        shield3 = load.getInt("shield3", 0);
        shield3royalstone = load.getInt("shield3royalstone", 0);
        shield4 = load.getInt("shield4", 0);

        watch1 = load.getInt("watch1", 0);
        watch1_1 = load.getInt("watch1_1", 0);
        watch1gold = load.getInt("watch1gold", 0);
        watch2 = load.getInt("watch2", 0);
        watch3 = load.getInt("watch3", 0);

        shovel1 = load.getInt("shovel1", 0);
        shovel1royalstone = load.getInt("shovel1royalstone", 0);
        shovel2 = load.getInt("shovel2", 0);
        shovel2gold = load.getInt("shovel2gold", 0);
        shovel3 = load.getInt("shovel3", 0);

        mask1 = load.getInt("mask1", 0);
        mask1whiteruby = load.getInt("mask1whiteruby", 0);
        mask2 = load.getInt("mask2", 0);

        crowngold = load.getInt("crowngold", 0);
        crownroyalstone = load.getInt("crownroyalstone", 0);
        crownwhiteruby = load.getInt("crownwhiteruby", 0);
    }
    void savedata(){
        SharedPreferences load = getSharedPreferences("Database", Context.MODE_PRIVATE);
        SharedPreferences.Editor save = load.edit();
        save.putInt("balance", balance);
        save.putInt("keys", keys);
        save.putInt("emeralds", emeralds);
        save.putInt("rubies", rubies);
        save.putInt("royalstones", royalstones);
        save.putInt("emeraldrings", emeraldrings);
        save.putInt("rubyrings", rubyrings);
        save.putInt("royalrings", royalrings);

        //SALVAGE RATE
        save.putInt("anvil1", anvil1);
        save.putInt("anvil2", anvil2);
        save.putInt("anvil3", anvil3);

        //INVENTORY SIZE
        save.putInt("backpack1", backpack1);
        save.putInt("backpack2", backpack2);
        save.putInt("backpack3", backpack3);
        save.putInt("backpack4", backpack4);
        save.putInt("backpack5", backpack5);
        save.putInt("backpack6", backpack6);
        save.putInt("backpack7", backpack7);
        save.putInt("backpack8", backpack8);
        save.putInt("backpack9", backpack9);

        //BALANCE HOLDERS
        save.putInt("pig1", pig1);
        save.putInt("pigroyalstone", pigroyalstone);

        save.putInt("vault", vault);
        save.putInt("vaultruby", vaultruby);

        save.putInt("bank1", bank1);
        save.putInt("bankgold", bankgold);

        //SHIELDS
        save.putInt("shield1", shield1);
        save.putInt("shield1_1", shield1_1);
        save.putInt("shield1_2", shield1_2);
        save.putInt("shield2", shield2);
        save.putInt("shield3", shield3);
        save.putInt("shield3royalstone", shield3royalstone);
        save.putInt("shield4", shield4);

        //WATCHES
        save.putInt("watch1", watch1);
        save.putInt("watch1gold", watch1gold);
        save.putInt("watch1_1", watch1_1);
        save.putInt("watch2", watch2);
        save.putInt("watch3", watch3);

        //SHOVELS
        save.putInt("shovel1", shovel1);
        save.putInt("shovel1royalstone", shovel1royalstone);
        save.putInt("shovel2", shovel2);
        save.putInt("shovel2gold", shovel2gold);
        save.putInt("shovel3", shovel3);

        //MASKS
        save.putInt("mask1", mask1);
        save.putInt("mask1whiteruby", mask1whiteruby);
        save.putInt("mask2", mask2);

        //CROWNS
        save.putInt("crowngold", crowngold);
        save.putInt("crownroyalstone", crownroyalstone);
        save.putInt("crownwhiteruby", crownwhiteruby);
    }

    @Override
    public void onBackPressed() {
        Intent intent = new Intent(Inventory.this, Main.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
        finish();
        startActivity(intent);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Set fullscreen
        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);
        // Set No Title
        this.requestWindowFeature(Window.FEATURE_NO_TITLE);
        setContentView(R.layout.activity_inventory);

        banneris = (ImageView)findViewById(R.id.banneris);

        leftBtn = (ImageButton)findViewById(R.id.leftBtn);
        mainBtn = (ImageButton)findViewById(R.id.mainBtn);
        rightBtn = (ImageButton)findViewById(R.id.rightBtn);

        box1 = (ImageButton)findViewById(R.id.box1);
        box2 = (ImageButton)findViewById(R.id.box2);
        box3 = (ImageButton)findViewById(R.id.box3);
        box4 = (ImageButton)findViewById(R.id.box4);
        box5 = (ImageButton)findViewById(R.id.box5);
        box6 = (ImageButton)findViewById(R.id.box6);
        box7 = (ImageButton)findViewById(R.id.box7);
        box8 = (ImageButton)findViewById(R.id.box8);
        box9 = (ImageButton)findViewById(R.id.box9);
        box10 = (ImageButton)findViewById(R.id.box10);
        box11 = (ImageButton)findViewById(R.id.box11);
        box12 = (ImageButton)findViewById(R.id.box12);
        box13 = (ImageButton)findViewById(R.id.box13);
        box14 = (ImageButton)findViewById(R.id.box14);
        box15 = (ImageButton)findViewById(R.id.box15);
        box16 = (ImageButton)findViewById(R.id.box16);
        box17 = (ImageButton)findViewById(R.id.box17);
        box18 = (ImageButton)findViewById(R.id.box18);
        box19 = (ImageButton)findViewById(R.id.box19);
        box20 = (ImageButton)findViewById(R.id.box20);
        box21 = (ImageButton)findViewById(R.id.box21);
        box22 = (ImageButton)findViewById(R.id.box22);
        box23 = (ImageButton)findViewById(R.id.box23);
        box24 = (ImageButton)findViewById(R.id.box24);
        box25 = (ImageButton)findViewById(R.id.box25);
        box26 = (ImageButton)findViewById(R.id.box26);
        box27 = (ImageButton)findViewById(R.id.box27);
        box28 = (ImageButton)findViewById(R.id.box28);
        box29 = (ImageButton)findViewById(R.id.box29);
        box30 = (ImageButton)findViewById(R.id.box30);
        box31 = (ImageButton)findViewById(R.id.box31);
        box32 = (ImageButton)findViewById(R.id.box32);
        box33 = (ImageButton)findViewById(R.id.box33);
        box34 = (ImageButton)findViewById(R.id.box34);
        box35 = (ImageButton)findViewById(R.id.box35);
        box36 = (ImageButton)findViewById(R.id.box36);
        box37 = (ImageButton)findViewById(R.id.box37);
        box38 = (ImageButton)findViewById(R.id.box38);
        box39 = (ImageButton)findViewById(R.id.box39);
        box40 = (ImageButton)findViewById(R.id.box40);
        box41 = (ImageButton)findViewById(R.id.box41);
        box42 = (ImageButton)findViewById(R.id.box42);
        box43 = (ImageButton)findViewById(R.id.box43);
        box44 = (ImageButton)findViewById(R.id.box44);
        box45 = (ImageButton)findViewById(R.id.box45);
        box46 = (ImageButton)findViewById(R.id.box46);
        box47 = (ImageButton)findViewById(R.id.box47);
        box48 = (ImageButton)findViewById(R.id.box48);
        box49 = (ImageButton)findViewById(R.id.box49);
        box50 = (ImageButton)findViewById(R.id.box50);
        box51 = (ImageButton)findViewById(R.id.box51);
        box52 = (ImageButton)findViewById(R.id.box52);
        box53 = (ImageButton)findViewById(R.id.box53);
        box54 = (ImageButton)findViewById(R.id.box54);
        box55 = (ImageButton)findViewById(R.id.box55);
        box56 = (ImageButton)findViewById(R.id.box56);
        box57 = (ImageButton)findViewById(R.id.box57);
        box58 = (ImageButton)findViewById(R.id.box58);
        box59 = (ImageButton)findViewById(R.id.box59);
        box60 = (ImageButton)findViewById(R.id.box60);
        box61 = (ImageButton)findViewById(R.id.box61);
        box62 = (ImageButton)findViewById(R.id.box62);
        box63 = (ImageButton)findViewById(R.id.box63);
        box64 = (ImageButton)findViewById(R.id.box64);
        box65 = (ImageButton)findViewById(R.id.box65);
        box66 = (ImageButton)findViewById(R.id.box66);
        box67 = (ImageButton)findViewById(R.id.box67);
        box68 = (ImageButton)findViewById(R.id.box68);
        box69 = (ImageButton)findViewById(R.id.box69);

        back1 = (ImageView)findViewById(R.id.back1);
        back2 = (ImageView)findViewById(R.id.back2);
        back3 = (ImageView)findViewById(R.id.back4);
        back4 = (ImageView)findViewById(R.id.back4);
        back5 = (ImageView)findViewById(R.id.back5);
        back6 = (ImageView)findViewById(R.id.back6);
        back7 = (ImageView)findViewById(R.id.back7);
        back8 = (ImageView)findViewById(R.id.back8);
        back9 = (ImageView)findViewById(R.id.back9);
        back10 = (ImageView)findViewById(R.id.back10);
        back11 = (ImageView)findViewById(R.id.back11);
        back12 = (ImageView)findViewById(R.id.back12);
        back13 = (ImageView)findViewById(R.id.back13);
        back14 = (ImageView)findViewById(R.id.back14);
        back15 = (ImageView)findViewById(R.id.back15);
        back16 = (ImageView)findViewById(R.id.back16);
        back17 = (ImageView)findViewById(R.id.back17);
        back18 = (ImageView)findViewById(R.id.back18);
        back19 = (ImageView)findViewById(R.id.back19);
        back20 = (ImageView)findViewById(R.id.back20);
        back21 = (ImageView)findViewById(R.id.back21);
        back22 = (ImageView)findViewById(R.id.back22);
        back23 = (ImageView)findViewById(R.id.back23);
        back24 = (ImageView)findViewById(R.id.back24);
        back25 = (ImageView)findViewById(R.id.back25);
        back26 = (ImageView)findViewById(R.id.back26);
        back27 = (ImageView)findViewById(R.id.back27);
        back28 = (ImageView)findViewById(R.id.back28);
        back29 = (ImageView)findViewById(R.id.back29);
        back30 = (ImageView)findViewById(R.id.back30);
        back31 = (ImageView)findViewById(R.id.back31);
        back32 = (ImageView)findViewById(R.id.back32);
        back33 = (ImageView)findViewById(R.id.back33);
        back34 = (ImageView)findViewById(R.id.back34);
        back35 = (ImageView)findViewById(R.id.back35);
        back36 = (ImageView)findViewById(R.id.back36);
        back37 = (ImageView)findViewById(R.id.back37);
        back38 = (ImageView)findViewById(R.id.back38);
        back39 = (ImageView)findViewById(R.id.back39);
        back40 = (ImageView)findViewById(R.id.back40);
        back41 = (ImageView)findViewById(R.id.back41);
        back42 = (ImageView)findViewById(R.id.back42);
        back43 = (ImageView)findViewById(R.id.back43);
        back44 = (ImageView)findViewById(R.id.back44);
        back45 = (ImageView)findViewById(R.id.back45);
        back46 = (ImageView)findViewById(R.id.back46);
        back47 = (ImageView)findViewById(R.id.back47);
        back48 = (ImageView)findViewById(R.id.back48);
        back49 = (ImageView)findViewById(R.id.back49);
        back50 = (ImageView)findViewById(R.id.back50);
        back51 = (ImageView)findViewById(R.id.back51);
        back52 = (ImageView)findViewById(R.id.back52);
        back53 = (ImageView)findViewById(R.id.back53);
        back54 = (ImageView)findViewById(R.id.back54);
        back55 = (ImageView)findViewById(R.id.back55);
        back56 = (ImageView)findViewById(R.id.back56);
        back57 = (ImageView)findViewById(R.id.back57);
        back58 = (ImageView)findViewById(R.id.back58);
        back59 = (ImageView)findViewById(R.id.back59);
        back60 = (ImageView)findViewById(R.id.back60);
        back61 = (ImageView)findViewById(R.id.back61);
        back62 = (ImageView)findViewById(R.id.back62);
        back63 = (ImageView)findViewById(R.id.back63);
        back64 = (ImageView)findViewById(R.id.back64);
        back65 = (ImageView)findViewById(R.id.back65);
        back66 = (ImageView)findViewById(R.id.back66);
        back67 = (ImageView)findViewById(R.id.back67);
        back68 = (ImageView)findViewById(R.id.back68);
        back69 = (ImageView)findViewById(R.id.back69);

        count1 = (TextView)findViewById(R.id.count1);
        count2 = (TextView)findViewById(R.id.count2);
        count3 = (TextView)findViewById(R.id.count3);
        count4 = (TextView)findViewById(R.id.count4);
        count5 = (TextView)findViewById(R.id.count5);
        count6 = (TextView)findViewById(R.id.count6);
        count7 = (TextView)findViewById(R.id.count7);
        count8 = (TextView)findViewById(R.id.count8);
        count9 = (TextView)findViewById(R.id.count9);
        count10 = (TextView)findViewById(R.id.count10);
        count11 = (TextView)findViewById(R.id.count11);
        count12 = (TextView)findViewById(R.id.count12);
        count13 = (TextView)findViewById(R.id.count13);
        count14 = (TextView)findViewById(R.id.count14);
        count15 = (TextView)findViewById(R.id.count15);
        count16 = (TextView)findViewById(R.id.count16);
        count17 = (TextView)findViewById(R.id.count17);
        count18 = (TextView)findViewById(R.id.count18);
        count19 = (TextView)findViewById(R.id.count19);
        count20 = (TextView)findViewById(R.id.count20);
        count21 = (TextView)findViewById(R.id.count21);
        count22 = (TextView)findViewById(R.id.count22);
        count23 = (TextView)findViewById(R.id.count23);
        count24 = (TextView)findViewById(R.id.count24);
        count25 = (TextView)findViewById(R.id.count25);
        count26 = (TextView)findViewById(R.id.count26);
        count27 = (TextView)findViewById(R.id.count27);
        count28 = (TextView)findViewById(R.id.count28);
        count29 = (TextView)findViewById(R.id.count29);
        count30 = (TextView)findViewById(R.id.count30);
        count31 = (TextView)findViewById(R.id.count31);
        count32 = (TextView)findViewById(R.id.count32);
        count33 = (TextView)findViewById(R.id.count33);
        count34 = (TextView)findViewById(R.id.count34);
        count35 = (TextView)findViewById(R.id.count35);
        count36 = (TextView)findViewById(R.id.count36);
        count37 = (TextView)findViewById(R.id.count37);
        count38 = (TextView)findViewById(R.id.count38);
        count39 = (TextView)findViewById(R.id.count39);
        count40 = (TextView)findViewById(R.id.count40);
        count41 = (TextView)findViewById(R.id.count41);
        count42 = (TextView)findViewById(R.id.count42);
        count43 = (TextView)findViewById(R.id.count43);
        count44 = (TextView)findViewById(R.id.count44);
        count45 = (TextView)findViewById(R.id.count45);
        count46 = (TextView)findViewById(R.id.count46);
        count47 = (TextView)findViewById(R.id.count47);
        count48 = (TextView)findViewById(R.id.count48);
        count49 = (TextView)findViewById(R.id.count49);
        count50 = (TextView)findViewById(R.id.count50);
        count51 = (TextView)findViewById(R.id.count51);
        count52 = (TextView)findViewById(R.id.count52);
        count53 = (TextView)findViewById(R.id.count53);
        count54 = (TextView)findViewById(R.id.count54);
        count55 = (TextView)findViewById(R.id.count55);
        count56 = (TextView)findViewById(R.id.count56);
        count57 = (TextView)findViewById(R.id.count57);
        count58 = (TextView)findViewById(R.id.count58);
        count59 = (TextView)findViewById(R.id.count59);
        count60 = (TextView)findViewById(R.id.count60);
        count61 = (TextView)findViewById(R.id.count61);
        count62 = (TextView)findViewById(R.id.count62);
        count63 = (TextView)findViewById(R.id.count63);
        count64 = (TextView)findViewById(R.id.count64);
        count65 = (TextView)findViewById(R.id.count65);
        count66 = (TextView)findViewById(R.id.count66);
        count67 = (TextView)findViewById(R.id.count67);
        count68 = (TextView)findViewById(R.id.count68);
        count69 = (TextView)findViewById(R.id.count69);
        
        loadData();
        setGUI();
        updateDisplay();

        leftBtn.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                //SHOP BUTTON

//                Intent intent = new Intent(Inventory.this, CaseCheck.class);
//                startActivity(intent);
            }
        });

        rightBtn.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Intent intent = new Intent(Inventory.this, Case.class);
                intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
                startActivity(intent);
            }
        });
    }
}